Inform user if search returned 0 results
hsjunnesson/wolfram.el pull request #11
Opened 2017-01-20 18:26 UTC by kaushalmodi

This commit fixes the issue where the "Contacting host: .." messages stays
hanging in the echo area whether or not a query ended up with non-zero result
pods.

Now after all the pods are retrieved and displayed in the WolframAlpha buffer,
the echo area is cleared out.. so the "Contacting host: .." message doesn't stay
hanging.

If the query results in 0 retrieved pods, a "No results for your query." is
printed in the WolframAlpha buffer, so that the user doesn't have to keep on
waiting for something to show up.

* wolfram--delete-in-progress-notification: New function. The logic for searching backward for the "(searching)" notification and removing
  it is moved to this function.

* wolfram--append-pods-to-buffer: Use the above function, remove the unused
  `buffer` argument.

* wolfram--query-callback: New function. Moved out the lambda callback function
as this separate function for better readability and "debuggablity".

2017-01-21 09:11 UTC, hsjunnesson requested changes
Good job, thanks for these changes. However, I have one small aesthetic change.

2017-01-21 09:11 UTC, hsjunnesson commented on wolfram.el
> +      (insert "\n"))))
Please change this back. I insert a newline after all of the pods have been inserted. This makes sure all pods have one newline before the next heading.
With this change, there are two newlines before the next heading.

2017-01-23 01:32 UTC, kaushalmodi commented on wolfram.el
> +      (insert "\n"))))
Nice catch! It was an overlook on my part. I did not intend the headings to be separated by 2 newlines. I have now fixed it.

2017-01-23 01:33 UTC, kaushalmodi commented
@hsjunnesson Thanks for the review. I have force-pushed the fix for the extra newline on the same branch.

2017-01-23 07:56 UTC, hsjunnesson approved these changes

2017-01-23 07:56 UTC, hsjunnesson commented
Looks great.

2017-01-23 07:56 UTC, merged